# Generated by Django 4.2.5 on 2023-10-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.BinaryField()),
                ('link_pag_web', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('social_media_link', models.TextField()),
                ('alumno', models.BooleanField()),
                ('imagen_perfil', models.ImageField(upload_to='profilepics')),
                ('admin', models.BooleanField()),
                ('institucion_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_pj', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='pjs')),
                ('fecha_comienzo', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('links', models.TextField()),
                ('terminado', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tasks.usuario')),
                ('id_respuestas', models.ManyToManyField(blank=True, to='tasks.post')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticias', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='news')),
                ('categoria', models.CharField(max_length=255)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BolsaTrabajoPost',
            fields=[
                ('id_postbt', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsa_trabajo_posts', to='tasks.usuario')),
                ('id_institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionBolsaTrabajo',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField()),
                ('textopos', models.TextField()),
                ('link_cv', models.CharField(max_length=255)),
                ('id_postbt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.bolsatrabajopost')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
    ]
