# Generated by Django 4.2.6 on 2023-10-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_noticia_categoria_alter_noticia_id_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
    ]
