# Generated by Django 4.2.6 on 2023-10-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='tasks\\static\x0cotonoticias'),
        ),
    ]
