# Generated by Django 4.2.5 on 2023-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_usuario_imagen_perfil_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('Noticia', 'Noticia'), ('Publicacion', 'Publicación')], default='Noticia', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='Instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='Twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
