# Generated by Django 4.2.7 on 2023-11-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_noticia_tipo_perfilusuario_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfilusuario'),
        ),
    ]
